export default {
  user: {
    uid: "",
    displayName: "",
    photoURL: "",
    email: "",
    emailVerified: false,
    phoneNumber: null,
    isAnonymous: false,
    tenantId: null,
    providerData: [
      {
        uid: "",
        displayName: "",
        photoURL: "",
        email: "",
        phoneNumber: null,
        providerId: "",
      },
    ],
    apiKey: "",
    appName: "",
    authDomain: "",
    stsTokenManager: {
      apiKey: "",
      refreshToken: "",
      accessToken: "",
      expirationTime: 1618579293033,
    },
    redirectEventId: null,
    lastLoginAt: "",
    createdAt: "",
    multiFactor: {
      enrolledFactors: [],
    },
  },
  token: "",
  quote: {
    _id: "KaIFTRaBv59T",
    tags: ["famous-quotes", "wisdom"],
    content: "Always seek out the seed of triumph in every adversity.",
    author: "Og Mandino",
    authorSlug: "og-mandino",
    length: 55,
  },
  fetchingQuote: false,
};
